development:
  clients:
    default:
      database:  coin_platform_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

test:
  clients:
    default:
      database:  coin_platform_test
      hosts:
        - localhost:27018
      options:
        read:
          mode: :primary
        max_pool_size: 1

development:
  clients:
    default:
      database:  coin_platform_test
      hosts:
        - localhost:27018
      options:
        read:
          mode: :primary
        max_pool_size: 1
